version: '3.9'
services:
  directory-negotiator-sync:
    build:
      context: .
    environment:
      - DIRECTORY_EMX2_ENDPOINT=https://directory-emx2-acc.molgenis.net/ERIC/directory/graphql
      - NEGOTIATOR_ENDPOINT=http://negotiator:8081/api/v3
      - NEGOTIATOR_CLIENT_AUTH_CLIENT_ID=123
      - NEGOTIATOR_CLIENT_AUTH_CLIENT_SECRET=123
      - NEGOTIATOR_CLIENT_AUTH_OIDC_TOKEN_ENDPOINT=http://oidc-cc-server-mock:80/connect/token
      - SYNC_JOB_SCHEDULE_INTERVAL=20
    networks:
      - directory-negotiator-sync
networks:
  directory-negotiator-sync:
    external: true
    name: docker-external_directory-negotiator-sync-test