version: '3.9'
services:
  directory-negotiator-sync:
    build:
      context: .
    volumes:
      - ./config.yaml:/opt/directory-negotiator-sync/config.yaml:ro
    networks:
      - directory-negotiator-sync
networks:
  directory-negotiator-sync:
    external: true
    name: docker-external_directory-negotiator-sync-test