version: '3.9'
services:
  oidc-cc-server-mock:
    container_name: oidc-cc-server-mock
    image: ghcr.io/soluto/oidc-server-mock:0.8.6
    ports:
      - '4011:80'
    environment:
      TZ: Europe/Rome
      ASPNETCORE_ENVIRONMENT: Development
      SERVER_OPTIONS_INLINE: |
        {
          "AccessTokenJwtType": "JWT",
          "Discovery": {
            "ShowKeySet": true
          },
          "Authentication": {
            "CookieSameSiteMode": "Lax",
            "CheckSessionCookieSameSiteMode": "Lax"
          }
        }
      LOGIN_OPTIONS_INLINE: |
        {
          "AllowRememberLogin": false
        }
      LOGOUT_OPTIONS_INLINE: |
        {
          "AutomaticRedirectAfterSignOut": true
        }
      API_SCOPES_INLINE: |
        - Name: negotiator_api
        - Name: negotiator_authz_management
        - Name: negotiator_resource_management
      API_RESOURCES_INLINE: |
        - Name: negotiator-api
          Scopes:
            - negotiator_api
            - negotiator_authz_management
            - negotiator_resource_management
          ApiSecrets:
          - negotiator-secret
      CLIENTS_CONFIGURATION_PATH: /config/clients.json
    volumes:
      - ./auth_server/config:/config:ro
    networks:
      - directory-negotiator-sync-test
  negotiator:
    container_name: negotiator
    image: negotiator-sync
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - TZ=Europe/Rome
      - PROFILE=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/negotiator
      - SPRING_DATASOURCE_USERNAME=negotiator
      - SPRING_DATASOURCE_PASSWORD=negotiator
      - SPRING_DATASOURCE_INITIALIZE=false
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_USER=negotiator
      - SPRING_FLYWAY_PASSWORD=negotiator
      - SPRING_FLYWAY_URL=jdbc:postgresql://postgres:5432/negotiator
      - SPRING_FLYWAY_LOCATIONS=classpath:db/migration/,db/dev/migration
      - NEGOTIATOR_FRONTENDURL=https://${HOST}
      - NEGOTIATOR_AUTHORIZATION_CLAIM=eduperson_entitlement
      - "NEGOTIATOR_AUTHORIZATION_ADMINCLAIMVALUE=urn:geant:bbmri-eric.eu:res:role_admin#perun.bbmri-eric.eu"
      - "NEGOTIATOR_AUTHORIZATION_RESEARCHERCLAIMVALUE=urn:geant:bbmri-eric.eu:res:role_researcher#perun.bbmri-eric.eu"
      - "NEGOTIATOR_AUTHORIZATION_BIOBANKERCLAIMVALUE=urn:geant:bbmri-eric.eu:res:role_representative#perun.bbmri-eric.eu"
      - "NEGOTIATOR_AUTHORIZATION_RESOURCECLAIMPREFIX=urn:geant:bbmri-eric.eu:group:bbmri:collections:BBMRI-ERIC%20Directory:"
      - NEGOTIATOR_AUTHORIZATION_SUBJECTCLAIM=sub
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_USERINFOURI=http://oidc-cc-server-mock/connect/userinfo
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI=http://oidc-cc-server-mock
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI=http://oidc-cc-server-mock/.well-known/openid-configuration/jwks
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_TYPE=jwt
    ports:
      - '8081:8081'
    networks:
      - directory-negotiator-sync-test
  emx2:
    image: molgenis/molgenis-emx2:latest
    environment:
      - TZ=Europe/Rome
      - MOLGENIS_POSTGRES_URI=jdbc:postgresql://postgres:5432/molgenis
      - MOLGENIS_POSTGRES_USER=molgenis
      - MOLGENIS_POSTGRES_PASS=molgenis
    #      - MOLGENIS_OIDC_CLIENT_ID=[]
    #      - MOLGENIS_OIDC_CLIENT_SECRET=[]
    #      - MOLGENIS_OIDC_CLIENT_NAME=MolgenisAuth
    #      - MOLGENIS_OIDC_DISCOVERY_URI=https://auth.molgenis.org/.well-known/openid-configuration/
    #      - MOLGENIS_OIDC_CALLBACK_URL=http://localhost:8080
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    networks:
      - directory-negotiator-sync-test
  postgres:
    image: postgres:15-alpine
    environment:
      - TZ=Europe/Rome
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./psql_data:/var/lib/postgresql/data
      - ./.docker/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - negotiator-db-data:/var/lib/postgresql/data
    command: -c 'shared_buffers=256MB' -c 'max_locks_per_transaction=1024'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 60s
      retries: 5
    networks:
      - directory-negotiator-sync-test
  ssr-catalogue:
    image: molgenis/ssr-catalogue
    ports:
      - "3000:3000"
    networks:
      - directory-negotiator-sync-test
  directory-negotiator-sync:
    build:
      context: ..
    environment:
      - TZ=Europe/Rome
      - DIRECTORY_EMX2_ENDPOINT=http://emx2:8080/ERIC/directory/graphql
      - NEGOTIATOR_ENDPOINT=http://negotiator:8081/api/v3
      - NEGOTIATOR_CLIENT_AUTH_CLIENT_ID=123
      - NEGOTIATOR_CLIENT_AUTH_CLIENT_SECRET=123
      - NEGOTIATOR_CLIENT_AUTH_OIDC_TOKEN_ENDPOINT=http://oidc-cc-server-mock:80/connect/token
      - SYNC_JOB_SCHEDULE_INTERVAL=20
    depends_on:
      negotiator:
        condition: service_healthy
      oidc-cc-server-mock:
        condition: service_healthy
    networks:
      - directory-negotiator-sync-test
networks:
  directory-negotiator-sync-test:
    driver: bridge
volumes:
  negotiator-db-data:

