version: '3.9'
services:
  directory-negotiator-sync:
    container_name: directory-negotiator-sync
    build:
      context: ..
    volumes:
      - ../config.yml:/opt/directory-negotiator-sync/config.yml:ro
    networks:
      - directory-negotiator-sync-network
networks:
  directory-negotiator-sync-network:
    external: true
    name: directory-negotiator-sync-test
volumes:
  negotiator-db-data:

