name: CI for integration tests execution and image build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *' # every day at 10am
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:
permissions: read-all
jobs:
  run-docker-compose-for-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Negotiator
        uses: actions/checkout@v2
        with:
          repository: BBMRI-ERIC/negotiator
          path: negotiator
      - name: Show negotiator path
        run:  | 
          ls
          cd negotiator
          pwd
          cd ..
          ls
          pwd
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Debug workspace
        run: |
          cd $GITHUB_WORKSPACE/negotiator_directory_sync/tests/compose
          cd ../../../negotiator
          ls
      - name: debug working dir
        run: | 
          cd $GITHUB_WORKSPACE
          ls
      - name: Run compose
        run: |  
         cd $GITHUB_WORKSPACE/negotiator_directory_sync/tests/compose
         docker compose -f docker-compose-integration-tests.yml  up -d
    
