name: CI for integration tests execution and image build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *' # every day at 10am
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:
permissions: read-all
jobs:
  run-docker-compose-for-tests:
    runs-on: ubuntu-latest
    steps:
     - name: Debug workspace
       run: |
        echo $GITHUB_WORKSPACE
     - name: Run compose
       run: |  
         cd $GITHUB_WORKSPACE
         ls
         docker-compose -f docker-compose-integration-tests.yml  up -d
    
