name: CI for integration tests execution and image build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *' # every day at 10am
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:
permissions: read-all
jobs:
  run-docker-compose-for-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Negotiator
        run: | 
         cd /opt
         git clone https://github.com/BBMRI-ERIC/negotiator.git
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Run compose
        run: |  
         cd $GITHUB_WORKSPACE/negotiator_directory_sync/tests/compose
         docker compose -f docker-compose-integration-tests.yml  up -d
      - name: Prepare python environment
        run: |
         cd $GITHUB_WORKSPACE
         pip install -r requirements.txt
      - name: Load test data for Directory
        run: |
         cd $GITHUB_WORKSPACE/negotiator_directory_sync/tests/scripts
         sleep 30
         python load_directory_data.py
         sleep 120
      - name: Run Integration tests
        run: | 
         cd $GITHUB_WORKSPACE/negotiator_directory_sync/tests
         pytest integration_tests.py
    
